Output demo.gif
Set FontSize 22
Set Width 600
Set Height 800
Set Theme "GruvboxDark"

Set Shell zsh
Type@40ms "shfl ~/projects/shfl/test.txt"
Sleep 500ms
Enter
Sleep 1s
Screenshot screenshots/one.png
Sleep 200ms
Type@200ms "jjj"
Sleep 400ms
Enter
Sleep 1s
Type@200ms "jjjjjjjj"
Sleep 400ms
Enter
Sleep 1s
Type@200ms "jjj"
Sleep 400ms
Type "9"
Sleep 500ms
Type@200ms "jjj"
Sleep 500ms
Type "3"
Sleep 500ms
Type@400ms "sssjjsss"
Screenshot screenshots/two.png
Sleep 500ms
Enter
Sleep 2s
